from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional, Any


class Level(str, Enum):
    LOW = "LOW"
    MED = "MED"
    HIGH = "HIGH"
    UNKNOWN = "UNKNOWN"


class F1Verdict(str, Enum):
    REAL = "REAL"
    KNOWN_SYNTHETIC = "KNOWN_SYNTHETIC"
    UNKNOWN_SYNTHETIC = "UNKNOWN_SYNTHETIC"
    UNKNOWN = "UNKNOWN"


@dataclass
class F1Evidence:
    """F1 Zero-Day Audio Evidence."""
    known_generator_similarity: Level = Level.UNKNOWN
    natural_speech_consistency: Level = Level.UNKNOWN
    verdict: F1Verdict = F1Verdict.UNKNOWN
    confidence: Optional[float] = None


class F2Pathway(str, Enum):
    DIRECT_GENUINE = "DIRECT_GENUINE"
    DIRECT_SYNTHETIC = "DIRECT_SYNTHETIC"
    REPLAYED_RECORDING = "REPLAYED_RECORDING"
    UNKNOWN = "UNKNOWN"


@dataclass
class F2Evidence:
    """F2 Replay Detection Evidence."""
    pathway: F2Pathway = F2Pathway.UNKNOWN
    reverb_detected: Optional[bool] = None
    confidence: Optional[float] = None


@dataclass
class F3Metadata:
    encoder: Optional[str] = None
    creation_time: Optional[str] = None
    resolution: Optional[str] = None


@dataclass
class F3Evidence:
    """F3 Source/Propagation Evidence."""
    match_found: Optional[bool] = None
    matched_seed_id: Optional[str] = None
    estimated_reencoding_stages: Optional[int] = None
    metadata: Optional[F3Metadata] = None


class F4Verdict(str, Enum):
    CONSISTENT = "CONSISTENT"
    MISMATCH_DETECTED = "MISMATCH_DETECTED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"


@dataclass
class F4Evidence:
    """F4 Eye Reflection Evidence."""
    frames_with_usable_eyes: Optional[int] = None
    catchlight_mismatch_flagged_frames: List[str] = field(default_factory=list)
    mismatch_rate: Optional[float] = None
    verdict: F4Verdict = F4Verdict.UNKNOWN


@dataclass
class F5Evidence:
    """Combined F1-F4 Evidence state."""
    f1: F1Evidence = field(default_factory=F1Evidence)
    f2: F2Evidence = field(default_factory=F2Evidence)
    f3: F3Evidence = field(default_factory=F3Evidence)
    f4: F4Evidence = field(default_factory=F4Evidence)


class AttributionCause(str, Enum):
    AI_SYNTHESIS = "AI_SYNTHESIS"
    CONVENTIONAL_EDITING = "CONVENTIONAL_EDITING"
    RE_RECORDED = "RE_RECORDED"
    UNKNOWN = "UNKNOWN"


@dataclass
class AttributionConflict:
    """Represents conflicting or uncertain evidence between modalities."""
    has_conflict: bool = False
    details: str = ""


@dataclass
class F5AttributionResult:
    """Attribution of the likely underlying technique/pathway of creation."""
    cause: AttributionCause = AttributionCause.UNKNOWN
    conflicts: AttributionConflict = field(default_factory=AttributionConflict)


class FinalVerdict(str, Enum):
    REAL = "REAL"
    MANIPULATED = "MANIPULATED"
    UNKNOWN = "UNKNOWN"


@dataclass
class F5FusionResult:
    """Final output generated by the P-Fusion engine."""
    final_verdict: FinalVerdict = FinalVerdict.UNKNOWN
    attribution: F5AttributionResult = field(default_factory=F5AttributionResult)
    evidence: F5Evidence = field(default_factory=F5Evidence)
